### ISSUE TITLE
Copying the Conf.php doesn't work with Docker Desktop

### ISSUE THREAD

**Issue by petsagouris** [DeAlexPesh/totum-docker-compose#1]
I am using PHPStorm to run the configurations.

https://github.com/DeAlexPesh/totum-docker-compose/blob/ba7e2bd81f8b32621875228100109115dc4f3168/compose/totum/totum.yml#L21

I have to change it to 
```
      - "./totum/Conf.php:/home/totum/totum/Conf.php"
```

**Comment by DeAlexPesh** [comment]
it's problem PHPStorm

**Comment by DeAlexPesh** [comment]
it's problem PHPStorm
